### ISSUE TITLE
How to use this to build a plugin system

### ISSUE THREAD

**Issue by anubisthejackle** [tormjens/eventy#20]
I, too, come from the WordPress world, so this project is perfect for me.

What I'm struggling with is trying to figure out how I might build a plugin system around this. I still haven't nailed down the Laravel execution path. Would I need to create a service provider and load it prior to the Eventy providers?

**Comment by Blair2004** [comment]
Hi, i'm also coming from WP, i've created a package with a plugin system, but... not really with this package. in fact, it could be used as hook API but, to build a plugin system here is basically what i've used : 
- FileSystem (to get all plugin config file as xml)
- XML parser
- Option system (i've build my own, to know which plugin should run automatically or not)

Maybe this could helps : https://github.com/Tendoo/cloud-breeze/blob/api-server/src/core/Services/Modules.php

**Comment by tormjens** [comment]
@anubisthejackle 

Laravel is already perfectly capable of acting as a plugin system itself with its auto-discovery features an all. 

Eventy would act as support to the awesome that is Laravel, so you can extend your packages from other packages. 

The way I have it set up in projects is that each "plugin" is its own composer package. If I want to install it to my application I simply require it via composer. Laravel's auto-discovery takes care of making sure the "plugin" is registered. Throughout the code in the plugin i make use of Eventy's actions and filters to offer abilities to extend them. If my plugin needs to extend functionality in another plugin I register my listeners in the service provider for my plugin.

For example: Plugin A has a class where it builds a query to fetch all published posts.

```php
class PostsQueryBuilder
{
    public function query()
    {
        return Post::where('published_at', '>', now());
    }
}
```

Using Eventy I can offer a filter for other plugins to hook in to this:

```php
use TorMorten\Eventy\Facades\Events as Eventy;
class PostsQueryBuilder
{
    public function query()
    {
        $query = resolve(Post::where('published_at', '>', now());
        return Eventy::filter('posts-query-builder:query', $query);
    }
}
```

Then, Plugin B comes along a needs to modify said query in other to only include posts with the word foo in the title.

In Plugin B's service provider (preferably in the `boot` method, since it will always be fired after Eventy has been made available) we'll add a listener for the event.

```
use TorMorten\Eventy\Facades\Events as Eventy;

class PluginBServiceProvider extends ServiceProvider 
{
    public function boot()
    {
        Eventy::addFilter('posts-query-builder:query', function($query) {
            return $query->where('title', 'like', '%foo%');
        });
    }
}
```

I hope this helps you on your way to building a plugin system in Laravel.
